apiVersion: v1
kind: Service
metadata:
  labels:
    app: db
  name: db
  namespace: vote
spec:
  selector:
    app: db
  ports:
  - port: 5432
    targetPort: 5432
    name: "db-service"
  type: ClusterIP #serviço privado dentro do cluster
