apiVersion: v1
kind: Service
metadata:
  labels:
    app: result
  name: result
  namespace: vote
spec:
  selector:
    app: result
  ports:
  - port: 5001
    targetPort: 80
    nodePort: 31000
    name: "result-service"
  type: NodePort #serviço privado dentro do cluster
