apiVersion: v1
kind: Service
metadata:
  labels:
    app: vote
  name: vote
  namespace: vote
spec:
  selector:
    app: vote
  ports:
  - port: 5000
    targetPort: 80
    nodePort: 31001
    name: "vote-service"
  type: NodePort #serviço privado dentro do cluster
