apiVersion: apps/v1
kind: Deployment
metadata:
  name: db
  labels: 
    app: db
  namespace: vote
spec:
  selector:
    matchLabels:
      app: vote
  template:
    metadata:
      labels:
        app: vote
    spec:
      containers:
      - name: postgres
        image: postgres:9.4
        env:
        - name: POSTGRES_USER
          value: postgres
        - name: POSTGRES_PASSWORD
          value: postgres
        ports:
        - containerPort: 5432
          name: postgres
        volumeMounts:
          - mountPath: /var/lib/postgresql/data
            name: db-data
        volumes:
        - name: db-data
          emptyDir: {}        
  replicas: 1
