apiVersion: v1
kind: Pod
metadata:
  name: mysql-pod
  labels:
    app: mysql-app
spec:
  containers:
    - name: mysql-container
      image: mysql:5
      env: #criando variável de ambiente
        - name: MYSQL_ROOT_PASSWORD
          value: password #define pro usuário root a senha "password"
        - name: MYSQL_DATABASE
          value: geek #nome do banco de dados